INSERT INTO PESSOA (NM_PESSOA, NU_CPF_CNPJ, TP_PESSOA) VALUES ('LETICIA CONDE', '48420978841', 'F');

INSERT INTO LIQUIDACAO (NM_LIQUIDACAO) VALUES ('Compensacao');
INSERT INTO LIQUIDACAO (NM_LIQUIDACAO) VALUES ('STR');
INSERT INTO LIQUIDACAO (NM_LIQUIDACAO) VALUES ('PAG');
INSERT INTO LIQUIDACAO (NM_LIQUIDACAO) VALUES ('Transferencia Interna');
INSERT INTO LIQUIDACAO (NM_LIQUIDACAO) VALUES ('PIX');


INSERT INTO LANCAMENTO (DATA_LANCAMENTO, VALOR_OPERACAO, LIQUIDACAO_CD_LIQUIDACAO, PESSOA_CD_PESSOA) VALUES ('20220728', 18, 1, 1);